name: cbs
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.750721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#B0A898'
    - '#000000'
    - '#F0E8D8'
  brandStrength: 0.508562
  lightness: 0.500822
  saturation: 0.506579
  rhythmicContrast: 0.502997
purpose:
  - name: null
    item: null
    url: null
