analytics: {}
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#B0A898'
    - '#000000'
    - '#F0E8D8'
  brandStrength: 0.741776
  lightness: 0.500822
  rhythmicContrast: 0.279838
  saturation: 1
cta: {}
layout_spectrum: 0.578125
name: cbs
opengraph: {}
purpose: {}
typography_spectrum: 0.750721
