analytics: {}
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#B0A898'
    - '#000000'
    - '#F0E8D8'
  brandStrength: 0.130757
  lightness: 1
  rhythmicContrast: 0.279838
  saturation: 1
cta: {}
layout_spectrum: 0.98602
name: cbs
opengraph: {}
purpose: {}
typography_spectrum: 0.750721
