analytics: {}
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#B0A898'
    - '#000000'
    - '#F0E8D8'
  brandStrength: 0.508562
  lightness: 0.500822
  rhythmicContrast: 0.502997
  saturation: 0.506579
cta: {}
layout_spectrum: 0.018836
name: cbs
opengraph: {}
purpose: {}
typography_spectrum: 0.750721
