name: cbs
favicon: null
layout_spectrum: 0.73893
typography_spectrum: 0.750721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#273751'
    - '#b7b7b7'
    - '#a16b00'
    - '#fdfe00'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
