name: cbs
favicon: null
layout_spectrum: 0.73893
typography_spectrum: 0.750721
title: CBS - Helping You Comply
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3cdee'
    - '#fffffd'
    - '#060b11'
    - '#82858a'
    - '#37669e'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
