analytics: {}
color:
  brandColors:
    - '#A8B0C0'
    - '#404820'
    - '#808850'
    - '#9DB14E'
    - '#000000'
  brandStrength: 0.130757
  lightness: 1
  rhythmicContrast: 0.279838
  saturation: 0.321918
cta: {}
layout_spectrum: 0.301809
name: cbs
opengraph: {}
purpose: {}
typography_spectrum: 0.750721
